### ISSUE TITLE
The name of Sequoia Landscape wallpapers are wrong

### ISSUE THREAD

**Issue by Zeroeggs** [zhongzachary/sonoma-screen-savers#5]
Now the preview image and full video of Sequoia Sunrise is displaying the Sequoia Morning.
The preview image from macOS system settings as below: 
<img width="248" alt="image" src="https://github.com/user-attachments/assets/e52979a4-9187-4230-a48b-565dbe47396e">

**Comment by zhongzachary** [comment]
thanks for flagging! corrected now
